package com.anz_bank.fraudmanagementdemo;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Fraud Case")
public class Fraud_Case implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Fraud Amount")
	private Double fraudAmount;

	@org.kie.api.definition.type.Label("Fraud Case ID")
	private java.lang.Integer fraudCaseID;

	@org.kie.api.definition.type.Label("Customer Account Number")
	private java.lang.String customerAccountNo;

	@org.kie.api.definition.type.Label("Credit Card Number")
	private java.math.BigInteger creditCardNo;

	@org.kie.api.definition.type.Label("Credit Card Status")
	private boolean creditCardStatus;

	@org.kie.api.definition.type.Label("Transaction Details")
	private java.lang.String transactionDetails;

	@org.kie.api.definition.type.Label("Is Fraud")
	private boolean isFraud;

	@org.kie.api.definition.type.Label("Contact Made")
	private java.lang.Boolean contactMade;

	@org.kie.api.definition.type.Label(value = "Is High Risk")
	private boolean isHighRisk;

	@org.kie.api.definition.type.Label(value = "Customer Segment")
	private java.lang.String customerSegment;

	public Fraud_Case() {
	}

	public java.lang.Integer getFraudCaseID() {
		return this.fraudCaseID;
	}

	public void setFraudCaseID(java.lang.Integer fraudCaseID) {
		this.fraudCaseID = fraudCaseID;
	}

	public java.lang.String getCustomerAccountNo() {
		return this.customerAccountNo;
	}

	public void setCustomerAccountNo(java.lang.String customerAccountNo) {
		this.customerAccountNo = customerAccountNo;
	}

	public java.math.BigInteger getCreditCardNo() {
		return this.creditCardNo;
	}

	public void setCreditCardNo(java.math.BigInteger creditCardNo) {
		this.creditCardNo = creditCardNo;
	}

	public boolean isCreditCardStatus() {
		return this.creditCardStatus;
	}

	public void setCreditCardStatus(boolean creditCardStatus) {
		this.creditCardStatus = creditCardStatus;
	}

	public java.lang.Double getFraudAmount() {
		return this.fraudAmount;
	}

	public void setFraudAmount(java.lang.Double fraudAmount) {
		this.fraudAmount = fraudAmount;
	}

	public java.lang.String getTransactionDetails() {
		return this.transactionDetails;
	}

	public void setTransactionDetails(java.lang.String transactionDetails) {
		this.transactionDetails = transactionDetails;
	}

	public boolean isIsFraud() {
		return this.isFraud;
	}

	public void setIsFraud(boolean isFraud) {
		this.isFraud = isFraud;
	}

	public java.lang.Boolean getContactMade() {
		return this.contactMade;
	}

	public void setContactMade(java.lang.Boolean contactMade) {
		this.contactMade = contactMade;
	}

	public boolean isIsHighRisk() {
		return this.isHighRisk;
	}

	public void setIsHighRisk(boolean isHighRisk) {
		this.isHighRisk = isHighRisk;
	}

	public java.lang.String getCustomerSegment() {
		return this.customerSegment;
	}

	public void setCustomerSegment(java.lang.String customerSegment) {
		this.customerSegment = customerSegment;
	}

	public Fraud_Case(java.lang.Double fraudAmount,
			java.lang.Integer fraudCaseID, java.lang.String customerAccountNo,
			java.math.BigInteger creditCardNo, boolean creditCardStatus,
			java.lang.String transactionDetails, boolean isFraud,
			java.lang.Boolean contactMade, boolean isHighRisk,
			java.lang.String customerSegment) {
		this.fraudAmount = fraudAmount;
		this.fraudCaseID = fraudCaseID;
		this.customerAccountNo = customerAccountNo;
		this.creditCardNo = creditCardNo;
		this.creditCardStatus = creditCardStatus;
		this.transactionDetails = transactionDetails;
		this.isFraud = isFraud;
		this.contactMade = contactMade;
		this.isHighRisk = isHighRisk;
		this.customerSegment = customerSegment;
	}

}